### PR TITLE
Performance_test

### PR DESCRIPTION
**Pull request by kojunsik**
Performance_test

### CODE REVIEW

**Comment by parkchamchi** [comment]
`__pycache__/` 제외해주세요

**Comment by kojunsik** [comment]
변경내용

**Comment by kojunsik** [comment]
matplotlib

**Comment by parkchamchi** [comment]
`migrations/` 제외되도록 해주세요

**Comment by kojunsik** [comment]
migrations/ 제외

**Comment by parkchamchi** [comment]
outdated

**Pull request closed without merging**
